import type { ClassData, ShiftData, SearchResult } from "@/types"

export const MOCK_CLASSES: ClassData[] = [
  {
    id: 1,
    name: "Enfermagem - Turma A",
    course: "Técnico em Enfermagem",
    progress: 85,
    status: "Em Andamento",
    studentsCount: 25,
    documentsApproved: 21,
    documentsTotal: 25,
    lastUpdate: "2024-01-15",
    issues: 1,
  },
  {
    id: 2,
    name: "Farmácia - Turma B",
    course: "Técnico em Farmácia",
    progress: 60,
    status: "Pendente Revisão",
    studentsCount: 18,
    documentsApproved: 11,
    documentsTotal: 18,
    lastUpdate: "2024-01-14",
    issues: 3,
  },
  {
    id: 3,
    name: "Radiologia - Turma C",
    course: "Técnico em Radiologia",
    progress: 100,
    status: "Concluído",
    studentsCount: 15,
    documentsApproved: 15,
    documentsTotal: 15,
    lastUpdate: "2024-01-13",
    issues: 0,
  },
  {
    id: 4,
    name: "Enfermagem - Turma D",
    course: "Técnico em Enfermagem",
    progress: 30,
    status: "Início do Processo",
    studentsCount: 22,
    documentsApproved: 7,
    documentsTotal: 22,
    lastUpdate: "2024-01-12",
    issues: 0,
  },
]

export const MOCK_SHIFTS: ShiftData[] = [
  {
    id: 1,
    date: "2024-01-16",
    time: "08:00 - 12:00",
    class: "Enfermagem - Turma A",
    preceptor: "Dra. Maria Silva",
    students: ["Ana Costa", "João Santos", "Maria Oliveira", "Pedro Lima"],
    location: "Hospital Central - UTI",
  },
  {
    id: 2,
    date: "2024-01-16",
    time: "14:00 - 18:00",
    class: "Farmácia - Turma B",
    preceptor: "Dr. Carlos Mendes",
    students: ["Lucia Ferreira", "Roberto Alves", "Sandra Rocha"],
    location: "Farmácia Escola",
  },
  {
    id: 3,
    date: "2024-01-17",
    time: "07:00 - 11:00",
    class: "Radiologia - Turma C",
    preceptor: "Dra. Patricia Gomes",
    students: ["Felipe Souza", "Carla Dias", "Marcos Pereira", "Julia Martins"],
    location: "Centro de Diagnóstico",
  },
  {
    id: 4,
    date: "2024-01-17",
    time: "13:00 - 17:00",
    class: "Enfermagem - Turma D",
    preceptor: "Dr. Antonio Ribeiro",
    students: ["Beatriz Castro", "Diego Nascimento", "Fernanda Torres"],
    location: "Hospital Central - Pediatria",
  },
  {
    id: 5,
    date: "2024-01-18",
    time: "08:00 - 12:00",
    class: "Enfermagem - Turma A",
    preceptor: "Dra. Maria Silva",
    students: ["Gabriel Moreira", "Helena Barbosa", "Igor Cardoso"],
    location: "Hospital Central - Emergência",
  },
]

export const MOCK_SEARCH_RESULTS: SearchResult[] = [
  { type: "Aluno", name: "Ana Costa", id: "001" },
  { type: "Turma", name: "Enfermagem - Turma A", id: "T001" },
  { type: "Curso", name: "Técnico em Enfermagem", id: "C001" },
  { type: "Preceptor", name: "Dra. Maria Silva", id: "P001" },
  { type: "Plantão", name: "Hospital Central - UTI", id: "PL001" },
]
